version: "3.9"
services:
  consumer:
    image: itziarmensaupc/edcconsumer:latest
    platform: linux/amd64
    ports:
      - "29191:29191"
      - "29193:29193"
      - "29194:29194"
      - "29291:29291"
      - "29192:29192"
      - "29195:29195"
    environment:
      - EDC_KEYSTORE_PASSWORD=123456
    volumes:
      - ./consumer/resources/configuration:/app/configuration
      - ./consumer/resources/certs:/app/certs
    networks:
      - edc_network

  provider:
    image: itziarmensaupc/edcprovider:latest
    platform: linux/amd64
    ports:
      - "19191:19191"
      - "19193:19193"
      - "19194:19194"
      - "19291:19291"
      - "19192:19192"
      - "19195:19195"
    environment:
      - EDC_KEYSTORE_PASSWORD=123456
    volumes:
      - ./provider/resources/configuration:/app/configuration
      - ./provider/resources/certs:/app/certs
    networks:
      - edc_network

networks:
  edc_network:
    driver: bridge