version: '3.8'

services:
  provider:
    image: provider-connector:latest
    ports:
      - "19191:19191"
      - "19193:19193"
      - "19194:19194"
      - "19291:19291"
      - "19192:19192"
      - "19195:19195"
    environment:
      - EDC_KEYSTORE_PASSWORD=123456
    volumes:
      - ./provider/resources/configuration:/app/configuration
      - ./provider/resources/certs:/app/certs
    networks:
      - edc_network

networks:
  edc_network:
    driver: bridge